plugins:
  - jekyll-remote-theme

remote_theme: chiefsan/minimal
show_downloads: true

baseurl: "" # the subpath of your site, e.g. /blog
logo: "https://upload.wikimedia.org/wikipedia/commons/6/61/Searchtool.svg"
